### ISSUE TITLE
Change Mapbox API key

### ISSUE THREAD

**Issue by rdebeasi** [unicef/magicbox-maps-prototype#9]
Hello! Just a friendly reminder that this application is using my Mapbox API key. I've kept this key active beyond the planned expiration date to avoid breaking your application, but please do replace the key with your own API key when you're able.

To make this change, you can either add the key as an environment variable (see this [old PR](https://github.com/unicef/magicbox-maps/pull/83)) or change [hard-coded key in App.js](https://github.com/unicef/magicbox-maps-prototype/blob/master/src/App.js#L34). This is public key, so it is safe to include it in code.

Thank you!

**Comment by mikefab** [comment]
@rdebeasi, we migrated this application to https://github.com/unicef/magicbox-maps-prototype and no longer use your key.

Please excuse me for not messaging you about this sooner, and thank you so much for letting us use your key in the first place.

p.s. We miss you.

**Comment by rdebeasi** [comment]
Awesome, thanks for letting me know! No worries at all about the delay. I know you're probably busy!

It does look like my key is [still in the prototype codebase](https://github.com/unicef/magicbox-maps-prototype/blob/master/src/App.js#L34) and in the version of the prototype that's on Azure (which I'm not linking because it may contain non-public data).

We miss you all too! Glad to see you're still building awesome stuff. :smile:

**Comment by mikefab** [comment]
Your key is still used in that app, however, we now use this instance to present: http://school-mapping-emergencies.eastus.cloudapp.azure.com:8080/

I simply need to destroy that old app that still uses your key.

**Comment by mikefab** [comment]
Sorry, I misunderstood. Will do.

**Comment by mikefab** [comment]
It is now removed from source code. I thought I'd fixed that before.

https://github.com/unicef/magicbox-maps-prototype/blob/master/src/App.js#L34

**Comment by rdebeasi** [comment]
Awesome, thanks so much! I'll leave that token up for another week or so to give folks a chance to update their dev environments, the Azure instance, etc. I'll disable it after that.

Thanks again! :)
